# Generated by Django 5.2.14 on 2026-05-26 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='work_orders.workorder'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usages', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='work_orders.workorder'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usages', to='inventory.part'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='work_orders.workorder'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status', 'deleted_at'], name='inventory_m_status_a09c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['stock', 'min_stock'], name='inventory_m_stock_0cce16_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uq_material_code_active'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['status', 'deleted_at'], name='inventory_p_status_e63c65_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['stock', 'min_stock'], name='inventory_p_stock_ec5a2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uq_part_code_active'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item_type', 'created_at'], name='inventory_s_item_ty_b8115f_idx'),
        ),
        migrations.AddIndex(
            model_name='workordermaterial',
            index=models.Index(fields=['work_order', 'created_at'], name='inventory_w_work_or_101a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderpart',
            index=models.Index(fields=['work_order', 'created_at'], name='inventory_w_work_or_567b4e_idx'),
        ),
    ]
