# Generated by Django 5.2.14 on 2026-05-28 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='material',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier_code',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='part',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='part',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier_code',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='InventoryFamily',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], db_index=True, default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.inventoryfamily'),
        ),
        migrations.AddField(
            model_name='part',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.inventoryfamily'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['family', 'status'], name='inventory_m_family__760910_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['supplier_code', 'status'], name='inventory_m_supplie_76685f_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['family', 'status'], name='inventory_p_family__eb3af1_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['supplier_code', 'status'], name='inventory_p_supplie_7196de_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__gt', ''), ('deleted_at__isnull', True)), fields=('barcode',), name='uq_material_barcode_active'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('qr_code__gt', '')), fields=('qr_code',), name='uq_material_qr_code_active'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__gt', ''), ('deleted_at__isnull', True)), fields=('barcode',), name='uq_part_barcode_active'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('qr_code__gt', '')), fields=('qr_code',), name='uq_part_qr_code_active'),
        ),
        migrations.AddIndex(
            model_name='inventoryfamily',
            index=models.Index(fields=['status', 'deleted_at'], name='inventory_i_status_833b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryfamily',
            index=models.Index(fields=['name', 'status'], name='inventory_i_name_9f077c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryfamily',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_inventory_family_name_active'),
        ),
    ]
