# Generated by Django 5.2.14 on 2026-05-26 23:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('entry_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('estimated_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=20)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('received', 'Recibido'), ('estimating', 'Presupuestando'), ('approved', 'Aprobado'), ('waiting_parts', 'Esperando piezas'), ('in_repair', 'En reparacion'), ('in_paint', 'En pintura'), ('finished', 'Terminado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], db_index=True, default='scheduled', max_length=30)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='appointments.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=20)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=80)),
                ('execution_order', models.PositiveIntegerField(default=1)),
                ('estimated_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_tasks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['work_order', 'execution_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'priority'], name='work_orders_status_832f28_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['vehicle', 'status'], name='work_orders_vehicle_7e1a87_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['estimated_delivery_date', 'status'], name='work_orders_estimat_a70774_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['client', 'entry_date'], name='work_orders_client__57006b_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['scheduled', 'received', 'estimating', 'approved', 'waiting_parts', 'in_repair', 'in_paint', 'finished'])), fields=('vehicle',), name='uq_active_work_order_vehicle'),
        ),
        migrations.AddIndex(
            model_name='workorderstatushistory',
            index=models.Index(fields=['work_order', 'created_at'], name='work_orders_work_or_4154dc_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderstatushistory',
            index=models.Index(fields=['new_status', 'created_at'], name='work_orders_new_sta_f30a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['work_order', 'execution_order'], name='work_orders_work_or_a0c008_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['status', 'sector'], name='work_orders_status_066402_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['responsible', 'status'], name='work_orders_respons_d4f8a4_idx'),
        ),
    ]
