# Generated by Django 5.2.14 on 2026-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_workordertask_estimated_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
