# Generated by Django 5.2.14 on 2026-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_tasktemplate_labor_cost_workordertask_labor_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('received', 'Recibido'), ('estimating', 'Presupuestando'), ('approved', 'Aprobado'), ('waiting_parts', 'Esperando piezas'), ('in_repair', 'En reparacion'), ('in_paint', 'En pintura'), ('finished', 'Terminado'), ('delivered', 'Entregado'), ('closed', 'Cerrada'), ('cancelled', 'Cancelado')], db_index=True, default='scheduled', max_length=30),
        ),
    ]
