# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkshopProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="AutoFlow Taller", max_length=180)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("whatsapp", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="workshop/")),
                ("order_header_title", models.CharField(default="Orden de trabajo", max_length=120)),
                ("estimate_header_title", models.CharField(default="Presupuesto", max_length=120)),
                ("invoice_header_title", models.CharField(default="Factura", max_length=120)),
                ("document_footer", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "perfil del taller",
                "verbose_name_plural": "perfil del taller",
            },
        ),
    ]
