# Generated by Django 5.2.14 on 2026-06-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopprofile',
            name='email_from_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='email_from_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='email_service_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='password_reset_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='password_reset_frontend_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='password_reset_token_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
