# Generated by Django 5.2.14 on 2026-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workshopprofile_email_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopprofile',
            name='mobile_api_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='mobile_default_api_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='mobile_max_photo_mb',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='mobile_offline_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='mobile_photo_upload_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='mobile_require_damage_photo',
            field=models.BooleanField(default=False),
        ),
    ]
