# Generated by Django 5.2.14 on 2026-05-30 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('merchant_order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Creado'), ('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Devuelto'), ('unknown', 'Desconocido')], db_index=True, default='created', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('init_point', models.URLField(blank=True, max_length=500)),
                ('sandbox_init_point', models.URLField(blank=True, max_length=500)),
                ('raw_preference', models.JSONField(blank=True, null=True)),
                ('raw_payment', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercadopago_payments', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='billing_mer_invoice_b18050_idx'), models.Index(fields=['external_reference', 'status'], name='billing_mer_externa_14f2ae_idx'), models.Index(fields=['payment_id', 'status'], name='billing_mer_payment_afdab7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('preference_id__gt', '')), fields=('preference_id',), name='uq_mp_preference_id'), models.UniqueConstraint(condition=models.Q(('payment_id__gt', '')), fields=('payment_id',), name='uq_mp_payment_id')],
            },
        ),
    ]
