# Generated by Django 5.2.14 on 2026-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_mercadopagopayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('pending', 'Pendiente'), ('authorized', 'Autorizado'), ('in_process', 'En proceso'), ('in_mediation', 'En mediacion'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Devuelto'), ('charged_back', 'Contracargo'), ('unknown', 'Desconocido')], db_index=True, default='created', max_length=20),
        ),
    ]
