# Generated by Django 5.2.14 on 2026-06-04 23:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('work_orders', '0003_tasktemplate_labor_cost_workordertask_labor_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReception',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reception_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('driver_name', models.CharField(blank=True, max_length=180)),
                ('driver_phone', models.CharField(blank=True, max_length=60)),
                ('driver_document', models.CharField(blank=True, max_length=60)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_level', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En recepcion'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='in_progress', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('apk', 'APK')], db_index=True, default='web', max_length=20)),
                ('mobile_device_id', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_receptions', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='vehicles.vehicle')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionInspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('result', models.CharField(choices=[('ok', 'Correcto'), ('future_attention', 'Requiere atencion futura'), ('immediate_attention', 'Requiere atencion inmediata'), ('not_checked', 'No revisado')], db_index=True, default='not_checked', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='reception.vehiclereception')),
            ],
            options={
                'ordering': ['section', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionDamage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('front', 'Frente'), ('rear', 'Trasera'), ('left', 'Lateral izquierdo'), ('right', 'Lateral derecho'), ('roof', 'Techo'), ('interior', 'Interior'), ('engine', 'Motor'), ('wheels', 'Ruedas'), ('other', 'Otro')], db_index=True, default='other', max_length=30)),
                ('part_name', models.CharField(blank=True, max_length=180)),
                ('damage_type', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Leve'), ('medium', 'Media'), ('high', 'Alta')], db_index=True, default='medium', max_length=20)),
                ('action_required', models.CharField(choices=[('repair', 'Reparar'), ('replace', 'Cambiar'), ('observe', 'Observar')], db_index=True, default='repair', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reception/damages/')),
                ('source', models.CharField(choices=[('web', 'Web'), ('apk', 'APK')], db_index=True, default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='reception.vehiclereception')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(default='Recepcion', max_length=120)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('ok', 'Correcto'), ('problem', 'Con problema'), ('not_checked', 'No revisado')], db_index=True, default='ok', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='reception.vehiclereception')),
            ],
            options={
                'ordering': ['section', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclereception',
            index=models.Index(fields=['vehicle', 'status'], name='reception_v_vehicle_445f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclereception',
            index=models.Index(fields=['client', 'received_at'], name='reception_v_client__b70fac_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclereception',
            index=models.Index(fields=['source', 'received_at'], name='reception_v_source_07bba0_idx'),
        ),
        migrations.AddIndex(
            model_name='receptioninspectionitem',
            index=models.Index(fields=['reception', 'result'], name='reception_r_recepti_fbef3d_idx'),
        ),
        migrations.AddIndex(
            model_name='receptiondamage',
            index=models.Index(fields=['reception', 'zone'], name='reception_r_recepti_91faef_idx'),
        ),
        migrations.AddIndex(
            model_name='receptiondamage',
            index=models.Index(fields=['action_required', 'severity'], name='reception_r_action__02bac5_idx'),
        ),
        migrations.AddIndex(
            model_name='receptionchecklistitem',
            index=models.Index(fields=['reception', 'status'], name='reception_r_recepti_7a6062_idx'),
        ),
    ]
