# Generated by Django 5.2.14 on 2026-06-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operativo', 'Operativo'), ('administracion', 'Administracion'), ('app_user', 'Usuario App')], default='app_user', max_length=20),
        ),
    ]
