# Generated by Django 5.2.14 on 2026-05-25 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('plate', models.CharField(max_length=30)),
                ('plate_normalized', models.CharField(db_index=True, editable=False, max_length=30)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], db_index=True, default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plate'],
                'indexes': [models.Index(fields=['client', 'status'], name='vehicles_ve_client__03db3e_idx'), models.Index(fields=['brand', 'model'], name='vehicles_ve_brand_28f206_idx'), models.Index(fields=['status', 'deleted_at'], name='vehicles_ve_status_6fca14_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plate_normalized',), name='uq_vehicle_plate_active')],
            },
        ),
    ]
