# Generated by Django 5.2.14 on 2026-05-27 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('dni', models.CharField(db_index=True, max_length=40)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('marital_status', models.CharField(choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a'), ('other', 'Otro')], default='single', max_length=20)),
                ('task_type', models.CharField(choices=[('painter', 'Pintor'), ('mechanic', 'Mecanico'), ('bodyworker', 'Chapista')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], db_index=True, default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='people_oper_last_na_4c2e69_idx'), models.Index(fields=['task_type', 'status'], name='people_oper_task_ty_55eb88_idx'), models.Index(fields=['status', 'deleted_at'], name='people_oper_status_c491c1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dni',), name='uq_operator_dni_active')],
            },
        ),
    ]
