# Generated by Django 5.2.14 on 2026-06-11 22:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='gpt-4o', max_length=80)),
                ('system_prompt', models.TextField(default='Sos un asistente operativo de taller automotor. Ayudas al equipo a consultar y gestionar vehiculos, ordenes de trabajo, turnos, repuestos, materiales, facturacion e indicadores. Respondes siempre en espanol, de forma clara y directa. Antes de ejecutar cualquier accion que modifique datos, siempre pedis confirmacion al usuario. Si no tenes datos suficientes para responder, lo indicas claramente en lugar de inventar informacion. Cuando mostras listas, usas formato estructurado. Si el usuario parece confundido, ofreces acciones rapidas para guiarlo.')),
                ('max_tokens', models.PositiveIntegerField(default=900)),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3)),
                ('enabled_tools', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'updated_at'], name='chatbot_cha_is_acti_94aa98_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uq_chatbot_single_active_config')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=120)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema'), ('tool', 'Tool')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chatbot_cha_user_id_2da3ea_idx'), models.Index(fields=['session_id', 'created_at'], name='chatbot_cha_session_117d99_idx'), models.Index(fields=['role', 'created_at'], name='chatbot_cha_role_a5481e_idx')],
            },
        ),
    ]
